### ISSUE TITLE
Add option to use a volume mount between app container and host

### ISSUE THREAD

**Issue by jameshalsall** [inviqa/harness-go#156]
Currently, the harness does not share a volume with the host, and so `ws recompile` is the defacto way to update what is in the app container. This was based on a simplified model, where all Go commands would usually be executed by the developer on their host machine.

However, it can cause some problems, particularly on Linux where there is no performance penalty for using a volume mount, but also because of minor differences in Go tools like `go mod tidy`, which has been known to receive bug fixes that change its behaviour.

Initially, we should add an option to this harness to allow developers to use [a volume mount](https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes) for the `app` container. We can then evaluate its impact on development workflow before deciding whether to make this the default or not.

If we decide to make this the default, then the `ws go` and `ws go docker` commands will need to be reshuffled as the default execution behaviour of `ws go` should be to run the command in the container. Another possibility would be to remove `ws go docker` and just have `ws go` execute the command in host or container based on the workspace configuration.

TODO:
- [x] add workspace attribute to opt-in for volume mount (done in https://github.com/inviqa/harness-go/pull/161)
- [x] rework the `ws go` and `ws go docker` commands so that they execute under `ws go` only, using the `app.mount_volume` attribute to determine where to run them (host / container)
- [x] make `app.mount_volume` default to `true`

**Comment by jbarton123** [comment]
On this, to start I think it's fine to have this as an elective (as @hgajjar I think has also alluded). We won't need mutagen since as you also point out, the volume of files in Go services is generally considerably smaller than with our PHP applications, so it shouldn't take a large amount of time to sync.

I agree that if this was to become the default, we should just remove the `ws go docker` command to avoid any confusion. We mention that on Linux, there is next to no performance penalty for using a volume mount. What sort of performance hit might we see for users using MacOS (asking the question, I don't think it will be anything to be concerned about however).

When something syncs (and this is probably again me asking a silly question), does the app automatically recompile?

**Comment by jameshalsall** [comment]
In terms of performance, there should be no-hit really. Given the Go application is compiled, there would possibly be a slightly longer compilation time because it's reading from a volume mount? 

We could write something to watch the Go files and automatically recompile the app when they change, but that feels too magicky to me at this stage, maybe we just change `ws recompile` to do an in-place recompile of the `app` binary on the container.

**Comment by jameshalsall** [comment]
When we shift to this as the default option (probably wise before we do a `1.0.0` stable release), we could use something like https://github.com/cespare/reflex.

and then in the dev Dockerfile, the entrypoint would look something like this instead:
```
ENTRYPOINT ["reflex", "--decoration=none", "-c", "/reflex.conf"]
```

**Comment by hgajjar** [comment]
> When we shift to this as the default option (probably wise before we do a `1.0.0` stable release), we could use something like https://github.com/cespare/reflex.
> 
> and then in the dev Dockerfile, the entrypoint would look something like this instead:
> 
> ```
> ENTRYPOINT ["reflex", "--decoration=none", "-c", "/reflex.conf"]
> ```

I like the idea of just changing the `ws recompile` to do an in-place recompile, or may be introduce a new command to do that (`ws app recompile`?).
But I don't like the idea of magically recompiling it on file changes.

**Comment by jameshalsall** [comment]
I am wondering what the downside of it would be, and couldn't think of one yesterday.

100% the in-place recompile would be good, but then the entrypoint would need to be something other than the app itself, at least I don't know of a way to stop and start PID1 without the container stopping.

**Comment by dantleech** [comment]
I'd avoid watching / recompiling. In VP we've added `ws integrate` which generates the code, formats the code, runs the unit + integration tests then builds the app in the container and restarts it.

**Comment by jameshalsall** [comment]
If you could share a link to that with me via DM that would be great 👍🏻

**Comment by jameshalsall** [comment]
Will close this now, as the work has been completed. We can revisit the auto-recompiling at a later date if necessary.
