### ISSUE TITLE
Do not remove the apt lists until after image-dependencies.sh is executed

### ISSUE THREAD

**Issue by jameshalsall** [inviqa/harness-go#35]
On https://github.com/inviqa/harness-go/blob/master/docker/image/app/Dockerfile.twig#L9 we remove the apt lists, but then later in the Dockerfile the contents of `image-dependencies.sh` may well install additional packages, requiring the lists files to be updated again. We should run the removal of apt lists only after the `image-dependencies.sh` is executed.

**Comment by kierenevans** [comment]
Better would be to just remove them twice - if you don't remove them in the `RUN` statement, they get committed to the layer that docker downloads, bloating the total image size.

**Comment by jameshalsall** [comment]
It's just having to know that you need to `apt-get update` in the `image-dependencies.sh` file, minor but not as nice DX. Maybe we could have a separate override specifically for installing additional apt packages that is executed before the removal of apt lists?

**Comment by kierenevans** [comment]
The following could work:
```
RUN apt-get update && /image-dependencies.sh && rm -rf /var/lib/apt/lists/*
```
Or simply setting an array attribute and looping over it in the Dockerfile.twig, avoiding the need for a file-based override.

**Comment by jameshalsall** [comment]
I like the array attribute idea, much better than the file override approach.

I was not sure if the existing `image-dependencies.sh` location within the Dockerfile was important, can't remember now :grin:. It might have been put after the git config + SSH key steps in case these were required for downloading dependencies.

Maybe we add an array attribute for additional packages required in the apt step, and then replace the `image-dependencies.sh` bit with a new array attribute for other arbitrary dependencies.
