### ISSUE TITLE
Make it easier to run `go install <module>` in the Docker image

### ISSUE THREAD

**Issue by jameshalsall** [inviqa/harness-go#69]
Currently, if you need to install something like `github.com/pact-foundation/pact-go`, or any Go module, in the Docker image you have to override the entire `Dockerfile.twig` file, and add

```
RUN go install github.com/pact-foundation/pact-go
```

Instead, we should add the option in the harness to list an arbitrary number of additional modules that will be installed using the above command, which will remove the need to override the entire `Dockerfile.twig` file.

**Comment by andytson-inviqa** [comment]
we have image-dependencies.sh already which allows this, though I don't mind another reimagining of this

**Comment by jameshalsall** [comment]
As we discussed on Slack (reiterating here for visibility):

There may be cases where `go mod install <foo>` needs to run after `go mod download`, and after `image-dependencies.sh`. However, it's probably much cleaner to try and rework both of these into harness attributes as a bunch of arbitrary steps that can be executed at each stage. The two stages could be defined as `pre-go-mod-download` and `post-go-mod-download` to allow projects to execute commands both before and after that step.

It was mentioned in https://github.com/inviqa/harness-go/issues/35 about using an array attribute in place of `image-dependencies.sh`, so this is essentially the same option for the `post-go-mod-download` step.
