### ISSUE TITLE
Move the Jenkinsfile.twig to the overlay directory

### ISSUE THREAD

**Issue by jameshalsall** [inviqa/harness-go#86]
Currently, the `Jenkinsfile.twig` template is in the skeleton directory, so it is only applied to the project root on initial creation. This makes it more difficult for projects to get upstream harness changes made in the Jenkinsfile (e.g. the addition of a new pipeline check).

We should move it to the overlay directory so changes are applied to the project each time `ws harness prepare` is executed.

~The drawback of having the `Jenkinsfile.twig` in the overlay directory is that if a project wants to make any changes to the Jenkinsfile to suit their needs then they have to override the template completely (otherwise `ws harness prepare` will override their Jenkinsfile).~

~We should expose attributes that allow projects to configure the Jenkinsfile stages and jobs without overriding the entire template to avoid this problem.~

**Comment by kierenevans** [comment]
I feel a file override is more easy to manage compared to attributes.

**Comment by jameshalsall** [comment]
Yeah maybe you are right 🤔. Let's rescope this to just moving the Jenkinsfile to the overlay, and see if a need arises for the attributes.

**Comment by jameshalsall** [comment]
It's already in the overlay directory, but doesn't get applied because we never rsync it.
