### ISSUE TITLE
Standardise `ws go` command naming to reflect where they are executed

### ISSUE THREAD

**Issue by jameshalsall** [inviqa/harness-go#89]
In #88 `ws go test coverage` was introduced which executes `go` on the host machine. This is different to the other `ws go ...` commands that execute `go` on the container.

To distinguish these in the command names we should decide on a naming convention, something like 
* `ws go ...` -> runs on the host
* `ws go docker ...` -> runs on the container

**Comment by jbarton123** [comment]
I agree with your suggestion of using the `docker` suffix on the workspace commands that will run on the container vs on the host machine. Will open up a PR to update our commands and look to have this in the 0.7 milestone.
